# Jupyter Notebook - Week 5, Book 6
## Playing with Series and DataFrames
### Task 1
Take the following Series:
```python
obj = pd.Series([4.5 , 7.2 , - 5.3 , 3.6], index = ['d', 'b', 'a', 'c'])
```
Now write a program that does the following things, printing the Series after each:
- reindex in reverse order
- drop the 'c' column
- sort the index alphabetically

In [3]:
import pandas as pd

def reindex_in_reverse_order(obj):
    reindexed_obj = obj.reindex(['c', 'a', 'b', 'd'])
    return reindexed_obj

def drop_c_column(obj):
    dropped_obj = obj.drop('c')
    return dropped_obj

def sort_index(obj):
    sorted_obj = obj.sort_index()
    return sorted_obj

def display_new_series(reindexed_obj, dropped_obj, sorted_obj):
    print(reindexed_obj)
    print("----------")   
    print(dropped_obj)
    print("----------")
    print(sorted_obj)
    
def main():
    obj = pd.Series([4.5, 7.2, - 5.3, 3.6], index = ['d', 'b', 'a', 'c'])
    print(obj)
    print("----------")
      
    reindexed_obj = reindex_in_reverse_order(obj)
    dropped_obj = drop_c_column(obj)
    sorted_obj = sort_index(obj)
    display_new_series(reindexed_obj, dropped_obj, sorted_obj)
    
main()

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64
----------
c    3.6
a   -5.3
b    7.2
d    4.5
dtype: float64
----------
d    4.5
b    7.2
a   -5.3
dtype: float64
----------
a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

### Task 2
Take the sample DataFrame we created earlier:
```python
data = {'state' : [ 'Ohio' , 'Ohio' , 'Ohio' , 'Nevada' , 'Nevada' , 'Nevada'],
'year' : [2000 , 2001 , 2002 , 2001 , 2002 , 2003],
'pop' : [1.5 , 1.7 , 3.6 , 2.4 , 2.9 , 3.2]}
frame = pd.DataFrame(data)
```
Now write a program that does the following things, printing the DataFrame after each:
- rearrange the DataFrame so that the columns are in the order : year, state, pop.
- add a column in fourth place called 'debt' and set the value of this to 0
- rank (don't sort) the DataFrame by the value of 'pop'

In [2]:
import pandas as pd

def rearrange_df(frame):
    rearranged_df = frame.reindex(columns = ['year', 'state', 'pop'])
    return rearranged_df

def add_debt_column(frame):
    frame['debt'] = 0
    return frame

def rank_df(frame):
    frame['pop_rank'] = frame['pop'].rank()
    return frame

def display_new_dfs(rearranged_df, df_with_debt, ranked_df):
    print(rearranged_df)
    print("----------")
    print(df_with_debt)
    print("----------")
    print(ranked_df)
    
def main():
    data = {'state' : [ 'Ohio' , 'Ohio' , 'Ohio' , 'Nevada' , 'Nevada' , 'Nevada'],
            'year' : [2000 , 2001 , 2002 , 2001 , 2002 , 2003],
            'pop' : [1.5 , 1.7 , 3.6 , 2.4 , 2.9 , 3.2]}
    frame = pd.DataFrame(data)
    print(frame)
    print("----------")
    
    rearranged_df = rearrange_df(frame)
    df_with_debt = add_debt_column(frame)
    ranked_df = rank_df(frame)
    display_new_dfs(rearranged_df, df_with_debt, ranked_df)

main()

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
----------
   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2
----------
    state  year  pop  debt  pop_rank
0    Ohio  2000  1.5     0       1.0
1    Ohio  2001  1.7     0       2.0
2    Ohio  2002  3.6     0       6.0
3  Nevada  2001  2.4     0       3.0
4  Nevada  2002  2.9     0       4.0
5  Nevada  2003  3.2     0       5.0
----------
    state  year  pop  debt  pop_rank
0    Ohio  2000  1.5     0       1.0
1    Ohio  2001  1.7     0       2.0
2    Ohio  2002  3.6     0       6.0
3  Nevada  2001  2.4     0       3.0
4  Nevada  2002  2.9     0       4.0
5  Nevada  2003  3.2     0       5.0